helmDefaults:
  verify: true
  wait: true
  atomic: true

repositories:
  - name: eck-crd
    url: git+https://github.com/8gears/eck-helm-chart.git@eck-crd?sparse=1
  - name: eck-cr
    url: git+https://github.com/8gears/eck-helm-chart.git@eck-cr?sparse=1
releases:
  - name: "eck"
    chart: "eck-crd/eck-crd"
    namespace: "default"
  - name: "elasticsearch"
    chart: "eck-cr/eck-cr"
    namespace: "default"
